### ISSUE TITLE
data_preparation.py fills RAM

### ISSUE THREAD

**Issue by danielhmorenog** [JadHADDAD92/covid-mask-detector#1]
**Describe the bug**
When I run data_preparation.py on my console whit python data_preparation.py comand it start to work, but when is unzip the folder non_mask_photos something happend that stop to do it and show on the console the error: view on the screenshot
**To Reproduce**
1. Go to cmd
2. type python data_preparation.py
3. wait a few minutes
4. see the error

**Expected behavior**
My expected behavior was that the code unzip all the data complete and show me a doc whit the dataset whit the id (0 or 1) (mask or not)

**Screenshots**
![error](https://user-images.githubusercontent.com/14266208/82764213-c7437000-9dd2-11ea-822b-1412d4be4a7e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 pro 1909
 - python 3.8.1

**Comment by JadHADDAD92** [comment]
This is happening because you are running out of RAM, and the DataFrame is too big.
I implemented it this way for simplicity.
I'll do another version that doesn't require to put the whole DataFrame in memory

**Comment by danielhmorenog** [comment]
OMG how much ram do you have? or better question. How is the minimun ram that I need? because I have 8 gb. Is to small?

**Comment by danielhmorenog** [comment]
BTW thanks for your fast answer

**Comment by JadHADDAD92** [comment]
should be good now

**Comment by danielhmorenog** [comment]
Thanks men, I gone a test now
