### ISSUE TITLE
Cannot train on multiGPU

### ISSUE THREAD

**Issue by stevenluzheng123456** [JadHADDAD92/covid-mask-detector#3]
Great work on Pytorch lightning, but I cannot train it on multi GPU(I set gpu=2), since Panda cannot support

**Comment by xsatria** [comment]
![image](https://user-images.githubusercontent.com/15814858/87194751-950ab500-c323-11ea-8d18-ba5a76f66847.png)

OS: Windows
On MaskDataset

input file isn't tensor.

thanks

**Comment by JadHADDAD92** [comment]
@xsatria I extracted your problem into a new issue #5 as it is unrelated to the current issue
